/**
 * 📧 Email Agent — Sends a formatted HTML summary email via Nodemailer
 */

import { sendEmail } from '../tools/email.js';

function buildEmailHtml(location, currentWeather, decisions) {
    const rows = decisions.map(d => `
        <tr style="border-bottom: 1px solid #eee;">
            <td style="padding: 12px; font-weight: bold;">${d.date}</td>
            <td style="padding: 12px; font-size: 24px; text-align: center;">${d.emoji}</td>
            <td style="padding: 12px;">
                <strong>${d.mode.toUpperCase()}</strong><br/>
                <span style="color: #666; font-size: 13px;">${d.reason}</span>
            </td>
            <td style="padding: 12px; color: #555;">${d.summary}</td>
        </tr>
    `).join('');

    return `
    <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #f8f9fa; border-radius: 12px; overflow: hidden;">
        <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 24px; color: white;">
            <h1 style="margin: 0; font-size: 22px;">🤖 Smart Commute Planner</h1>
            <p style="margin: 8px 0 0; opacity: 0.9;">📍 ${location}</p>
        </div>

        <div style="padding: 20px;">
            <div style="background: white; border-radius: 8px; padding: 16px; margin-bottom: 16px; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">
                <h3 style="margin: 0 0 8px; color: #333;">Current Weather</h3>
                <p style="margin: 0; color: #555;">
                    🌡️ ${currentWeather.tempC}°C (Feels like ${currentWeather.feelsLikeC}°C) · 
                    💧 ${currentWeather.humidity}% humidity · 
                    ${currentWeather.description}
                </p>
            </div>

            <div style="background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">
                <h3 style="margin: 0; padding: 16px 16px 8px; color: #333;">3-Day Commute Plan</h3>
                <table style="width: 100%; border-collapse: collapse;">
                    <thead>
                        <tr style="background: #f1f3f4; font-size: 13px; color: #666;">
                            <th style="padding: 8px 12px; text-align: left;">Date</th>
                            <th style="padding: 8px 12px; text-align: center;">Mode</th>
                            <th style="padding: 8px 12px; text-align: left;">Decision</th>
                            <th style="padding: 8px 12px; text-align: left;">Weather</th>
                        </tr>
                    </thead>
                    <tbody>
                        ${rows}
                    </tbody>
                </table>
            </div>

            <p style="margin: 16px 0 0; color: #999; font-size: 12px; text-align: center;">
                Generated by Smart Commute Planner · ${new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}
            </p>
        </div>
    </div>
    `;
}

export async function run(location, currentWeather, decisions, recipientEmail) {
    console.log(`\n---------📧 EMAIL AGENT-------`);
    console.log(`Sending summary to ${recipientEmail}...`);

    const html = buildEmailHtml(location, currentWeather, decisions);
    const subject = `🤖 Your 3-Day Commute Plan for ${location}`;

    const result = await sendEmail(recipientEmail, subject, html);

    if (result.success) {
        console.log(`✅ Email sent! (ID: ${result.messageId})`);
    } else {
        console.log(`❌ Email failed: ${result.error}`);
    }
    console.log(`---------------------`);

    return result;
}
